# Generated by Django 4.2 on 2023-04-07 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Gist_App', '0004_alter_gist_title_gistcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gistcomment',
            name='parent',
        ),
        migrations.AlterField(
            model_name='gist',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4),
        ),
    ]
