# Generated by Django 4.2 on 2023-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gist_App', '0006_gistcomment_parent_alter_gistcomment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gistcomment',
            old_name='comment',
            new_name='gist',
        ),
        migrations.AddField(
            model_name='gistcomment',
            name='content',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
