# Generated by Django 4.2 on 2023-04-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gist_App', '0010_alter_gist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gist',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
