# Generated by Django 4.2 on 2023-04-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
