# Generated by Django 4.2 on 2023-04-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_App', '0002_myuser_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_veryfied',
            field=models.BooleanField(default=False),
        ),
    ]
