# Generated by Django 4.2 on 2023-04-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post_App', '0005_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='gist',
            new_name='post',
        ),
    ]
